### ISSUE TITLE
Fix - Monk cant pick up the items for the first quest.

### ISSUE THREAD

**Issue by sergemanuel** [AshamaneProject/AshamaneCore#1020]
**Description:**

When monk starts, the first quest with objetives loot a handwrap is imposible to monk complete that because the gameobject giver of the items is not given to the monk at all. I run this script and its given de item, the when equip them, the quest complete by the kill credit on equip main weapon and off.

Here the script
UPDATE `gameobject_loot_template` SET `Entry`='40856', `Item`='77279', `Reference`='0', `Chance`='100', `QuestRequired`='1', `LootMode`='1', `GroupId`='0', `MinCount`='1', `MaxCount`='1', `Comment`=NULL WHERE (`Entry`='40856') AND (`Item`='73209');
DELETE FROM gameobject_loot_template WHERE Entry='40856' and Item= '77278';
INSERT INTO `gameobject_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('40856', '77278', '0', '100', '1', '1', '0', '1', '1', NULL);  

Please test it and i hope this work for you guys.

**Comment by cooler-SAI** [comment]
fixed, thanks

**Comment by sergemanuel** [comment]
Hi cooler-sai, you going to use the script o simple fix by other and close this issue(fix), i asking just to know if the script works or was a mistake.

/salute

**Comment by cooler-SAI** [comment]
I made the same fix

**Comment by Szone** [comment]
![image](https://user-images.githubusercontent.com/2180820/39677914-d397730a-518b-11e8-9f60-7f0fd5f7e5de.png)
 
Still not working with last rev of Core and DB.

**Comment by cooler-SAI** [comment]
![wowscrnshot_050718_123516](https://user-images.githubusercontent.com/812439/39695427-32f80f32-51f3-11e8-9f89-f5c19c20b402.jpg)
![wowscrnshot_050718_123603](https://user-images.githubusercontent.com/812439/39695428-331a35b2-51f3-11e8-817a-b8722afa7f8e.jpg)

**Comment by Szone** [comment]
@cooler-SAI  works only with .gm on.
