### ISSUE TITLE
Error with ADB_world_820.00.sql

### ISSUE THREAD

**Issue by Hooaah** [AshamaneProject/AshamaneCore#215]
<!--- (**********************************)
      (** Fill in the following fields **)
      (**********************************)
      (When I start world server to populate world, it crashes and gives world error.
Applying of file 'ADB_world_820.00.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not populate the World database, see log for details.

**Comment by Hooaah** [comment]
Applying of file 'ADB_world_820.00.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not populate the World database, see log for details.

**Comment by Traesh** [comment]
Please provide the logs, was your database empty ?

**Comment by Daniel25** [comment]
> Applying of file 'ADB_world_820.00.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
> Could not populate the World database, see log for details.

I think that your problem is memory in mysql,default is low.Try to change `max_allowed_packets`=500 M in the ini or config file of mysql installation. I had that issue and it worked. World db is 400 MB...

**Comment by Hooaah** [comment]
TrinityCore rev. 63eb69a9a04a 2020-04-23 22:04:45 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file C:/Users/hooaa/Desktop/BFA/Core/worldserver.conf.
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.66.0
Updating Auth database...
>> Auth database is up-to-date! Containing 7 new and 0 archived updates.
Updating Character database...
>> Applying update "2020_04_20_00_characters.sql" 'FB2C3D6'...
Warning: Using a password on the command line interface can be insecure.

ERROR 1060 (42S21) at line 1: Duplicate column name 'auctionHouseId'


Applying of file 'C:/Ashamane/sql/ashamane/characters/2020_04_20_00_characters.sql' to database 'characters' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the Character database, see log for details.


No errors in DBError logs.

**Comment by Hooaah** [comment]
Started over now I get this message while populating  and yes Daniel25, I changed to 500m before this issue.


TrinityCore rev. 63eb69a9a04a 2020-04-23 22:04:45 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file C:/Users/hooaa/Desktop/BFA/Core/worldserver.conf.
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.66.0
Database "auth" does not exist, do you want to create it? [yes (default) / no]: 
Creating database "auth"...
Warning: Using a password on the command line interface can be insecure.


Done.
Database "characters" does not exist, do you want to create it? [yes (default) / no]: 
Creating database "characters"...
Warning: Using a password on the command line interface can be insecure.


Done.
Database "world" does not exist, do you want to create it? [yes (default) / no]: 
Creating database "world"...
Warning: Using a password on the command line interface can be insecure.


Done.
Database "hotfixes" does not exist, do you want to create it? [yes (default) / no]: 
Creating database "hotfixes"...
Warning: Using a password on the command line interface can be insecure.


Done.
Database Auth is empty, auto populating it...
>> Applying 'C:/Ashamane/sql/base/auth_database.sql'...
Warning: Using a password on the command line interface can be insecure.


>> Done!
Database Character is empty, auto populating it...
>> Applying 'C:/Ashamane/sql/base/characters_database.sql'...
Warning: Using a password on the command line interface can be insecure.


>> Done!
Database World is empty, auto populating it...
>> Applying 'ADB_world_820.00.sql'...
Warning: Using a password on the command line interface can be insecure.

ERROR 2006 (HY000) at line 23912: MySQL server has gone away


Applying of file 'ADB_world_820.00.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not populate the World database, see log for details.

**Comment by mcsescott** [comment]
I opened the same issue yesterday, and there was a fix put in with the new commit today (0b0c749), but I rebuilt today and am still getting the error (I commented on my closed issue, but will upload the server log here as well).

To bypass it, I just cleared out the text file before I look at the database errors in depth.  It appears it has to do with auctionhouse stuff, and with a new server I am not using an AH, so it doesn't bother me at the moment.

[Server.log](https://github.com/AshamaneProject/AshamaneCore/files/4532062/Server.log)

**Comment by Daniel25** [comment]
> I opened the same issue yesterday, and there was a fix put in with the new commit today ([0b0c749](https://github.com/AshamaneProject/AshamaneCore/commit/0b0c749b718d844326f54e11c32a6b4868bc2607)), but I rebuilt today and am still getting the error (I commented on my closed issue, but will upload the server log here as well).
> 
> To bypass it, I just cleared out the text file before I look at the database errors in depth. It appears it has to do with auctionhouse stuff, and with a new server I am not using an AH, so it doesn't bother me at the moment.
> 
> [Server.log](https://github.com/AshamaneProject/AshamaneCore/files/4532062/Server.log)

For your error with updating the db,I fixed it with empty characters db and then worldserver.exe populeted it and updated it ok (but you lose all info in characters db,characters created,etc...).
By the way that is because you tryed to use the same update two times,maybe emptying that table only the issue is solvented (dunno why trinity create always updates which cant be applyed more than one time...).

@Hooaah  that error is the same that I told you, you need to change max_allowe_packets,maybe you didnt save the file when you did it....
https://www.alvarodeleon.net/solucionar-error-2006-hy000-mysql-server-has-gone-away-en-mysql-mariadb/

**Comment by Hooaah** [comment]
@Hooaah that error is the same that I told you, you need to change max_allowe_packets,maybe you didnt save the file when you did it....
https://www.alvarodeleon.net/solucionar-error-2006-hy000-mysql-server-has-gone-away-en-mysql-mariadb/

# The maximum size of one packet or any generated or intermediate string, or any parameter sent by the
# mysql_stmt_send_long_data() C API function.
max_allowed_packet=500M

@Daniel25 As you can see i have packets set to 500 and still same issue.

**Comment by Daniel25** [comment]
@Hooaah I wasnt saying that you didn't but maybe you can increment it more,dunno what way it works but someone in other conversation said he incremented more than 500,nvm... I have emptyed the world db now because I added any fix which didnt work and with world db empty the worldserver.exe populet it and updated it good.

**Comment by Hooaah** [comment]
@Daniel25 Ok, I'll try again

**Comment by Hooaah** [comment]
Well tried to increase packets several times up to 1000m and still getting the same error.

**Comment by Hooaah** [comment]
Now i get a different error in the DB errors.

[1146] Table 'world.updates_include' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

**Comment by mcsescott** [comment]
Hooaah - Did you drop the tables beforehand?

**Comment by Hooaah** [comment]
Yes I did

**Comment by Daniel25** [comment]
> Now i get a different error in the DB errors.
> 
> [1146] Table 'world.updates_include' doesn't exist
> Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

That error is telling you that table updates_include doesnt exist in your db world...That can mean 2 things:
1-  You are using a diferent db world to ADB_world_820.00.sql.
or
2- Your db world got broken.

The best thing that you can do everytime that you try to populate your db world and you get a error,it is empty it before of every try so you are sure that its a clear population in everytime.If you dont,you will get similar erros,duplicated entry error,etc... The most of sql patch are done to be introduced one time only and if you introduce it a second time it will cause errors...That is why you need to do clean db installation everytime you try it and you get a error.

**Comment by Hooaah** [comment]
Well figured out issue and it was none of the above, it was ADB_world_820.00.sql was creating 2 different World schema and causing the issue. renamed schema's and everything started working
